#!/usr/bin/env python3
"""Extract a small subset of each datasource for integration testing.

For each datasource in config.json, this script:
1. Finds all rows whose PROPERTY_VALUE matches any of the test examples
   in tests/old_zooma_examples/text_to_map.tsv
2. Adds a random sample of 100 additional rows from each datasource
3. Writes the result as a gzipped file in tests/old_zooma_examples/data/

The output files are identical in format to the originals (same headers,
same delimiter) so the app can load them as-is.
"""

import csv
import gzip
import json
import os
import random
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(REPO_ROOT, "config.json")
DATA_DIR = os.path.join(REPO_ROOT, "data")
TEST_TSV = os.path.join(REPO_ROOT, "tests", "old_zooma_examples", "text_to_map.tsv")
OUT_DIR = os.path.join(REPO_ROOT, "tests", "old_zooma_examples", "data")

RANDOM_SAMPLE_SIZE = 100
RANDOM_SEED = 42


def load_test_values():
    """Load propertyValue values from the test input TSV."""
    values = set()
    with open(TEST_TSV, "r") as f:
        reader = csv.reader(f, delimiter="\t")
        header = next(reader)
        for row in reader:
            if row:
                values.add(row[0].strip().lower())
    return values


def detect_delimiter(header_line):
    """Same heuristic as MappingTable.java: more commas → CSV, else TSV."""
    n_commas = header_line.count(",")
    n_tabs = header_line.count("\t")
    return "," if n_commas > n_tabs else "\t"


def find_property_value_col(headers, column_map, delimiter):
    """Find the column index that maps to PROPERTY_VALUE."""
    # Build the reverse mapping like the Java code does
    col_names = {
        "STUDY": "STUDY",
        "BIOENTITY": "BIOENTITY",
        "PROPERTY_TYPE": "PROPERTY_TYPE",
        "PROPERTY_VALUE": "PROPERTY_VALUE",
        "SEMANTIC_TAG": "SEMANTIC_TAG",
        "ANNOTATOR": "ANNOTATOR",
        "ANNOTATION_DATE": "ANNOTATION_DATE",
    }
    if column_map:
        # column_map maps: source_header -> canonical_name
        # e.g. {"Disease trait": "PROPERTY_VALUE", "EFO URI": "SEMANTIC_TAG"}
        for src_header, canonical in column_map.items():
            col_names[canonical] = src_header

    target_header = col_names.get("PROPERTY_VALUE", "PROPERTY_VALUE")
    for i, h in enumerate(headers):
        if h.strip() == target_header:
            return i
    return None


def process_datasource(ds_name, ds_config, test_values):
    """Extract matching + random rows for one datasource."""
    filename = ds_config["import_url"].split("/")[-1] + ".gz"
    filepath = os.path.join(DATA_DIR, filename)

    if not os.path.exists(filepath):
        print(f"  SKIP {ds_name}: {filename} not found")
        return None, None

    column_map = ds_config.get("column_map", {})

    with gzip.open(filepath, "rt", errors="replace") as f:
        header_line = f.readline()
        if not header_line:
            print(f"  SKIP {ds_name}: empty file")
            return None, None

        delimiter = detect_delimiter(header_line)
        headers = header_line.rstrip("\n\r").split(delimiter)
        pv_col = find_property_value_col(headers, column_map, delimiter)

        if pv_col is None:
            print(f"  WARN {ds_name}: no PROPERTY_VALUE column found in {headers}")
            pv_col = 0  # fallback to first column

        matched_rows = []
        other_rows = []

        for line in f:
            line_stripped = line.rstrip("\n\r")
            if not line_stripped:
                continue
            fields = line_stripped.split(delimiter)
            if pv_col < len(fields):
                pv = fields[pv_col].strip().lower()
                if pv in test_values:
                    matched_rows.append(line_stripped)
                else:
                    other_rows.append(line_stripped)
            else:
                other_rows.append(line_stripped)

    # Random sample from non-matched rows
    rng = random.Random(RANDOM_SEED)
    sample_size = min(RANDOM_SAMPLE_SIZE, len(other_rows))
    sampled_rows = rng.sample(other_rows, sample_size) if sample_size > 0 else []

    # Combine: comment + header + matched + sample
    n_matched = len(matched_rows)
    n_sampled = len(sampled_rows)
    comment = (
        f"# Sample extract for testing — {n_matched} matched + {n_sampled} random rows "
        f"from {ds_name}. Generated by tests/extract_test_data.py"
    )
    all_rows = [comment, header_line.rstrip("\n\r")] + matched_rows + sampled_rows

    return filename, all_rows


def main():
    random.seed(RANDOM_SEED)

    with open(CONFIG_PATH) as f:
        config = json.load(f)

    test_values = load_test_values()
    print(f"Loaded {len(test_values)} test property values")

    os.makedirs(OUT_DIR, exist_ok=True)

    total_matched = 0
    total_sampled = 0

    for ds_name, ds_config in config["datasources"].items():
        filename, rows = process_datasource(ds_name, ds_config, test_values)
        if rows is None:
            continue

        outpath = os.path.join(OUT_DIR, filename)
        with gzip.open(outpath, "wt") as f:
            for row in rows:
                f.write(row + "\n")

        data_count = len(rows) - 2  # minus comment and header
        print(f"  {ds_name}: {data_count} rows → {filename}")
        total_sampled += data_count

    # Also copy the gwas_catalog.tsv.gz if it exists (not in config but in data/)
    gwas_extra = os.path.join(DATA_DIR, "gwas_catalog.tsv.gz")
    if os.path.exists(gwas_extra):
        with gzip.open(gwas_extra, "rt", errors="replace") as f:
            header_line = f.readline()
            delimiter = detect_delimiter(header_line)
            headers = header_line.rstrip("\n\r").split(delimiter)
            # This file has PROPERTY_VALUE, SEMANTIC_TAG columns
            pv_col = None
            for i, h in enumerate(headers):
                if h.strip() == "PROPERTY_VALUE":
                    pv_col = i
                    break
            if pv_col is None:
                pv_col = 0

            matched = []
            other = []
            for line in f:
                ls = line.rstrip("\n\r")
                if not ls:
                    continue
                fields = ls.split(delimiter)
                if pv_col < len(fields) and fields[pv_col].strip().lower() in test_values:
                    matched.append(ls)
                else:
                    other.append(ls)

        rng = random.Random(RANDOM_SEED)
        sampled = rng.sample(other, min(RANDOM_SAMPLE_SIZE, len(other)))
        comment = (
            f"# Sample extract for testing \u2014 {len(matched)} matched + {len(sampled)} random rows "
            f"from gwas_catalog. Generated by tests/extract_test_data.py"
        )
        all_rows = [comment, header_line.rstrip("\n\r")] + matched + sampled

        outpath = os.path.join(OUT_DIR, "gwas_catalog.tsv.gz")
        with gzip.open(outpath, "wt") as f:
            for row in all_rows:
                f.write(row + "\n")
        print(f"  gwas_catalog (extra): {len(all_rows)-1} rows")

    print(f"\nDone. Test data written to {OUT_DIR}")


if __name__ == "__main__":
    main()
