apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: caddy-data
          emptyDir: {}
        - name: caddy-config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      containers:
        - name: web
          image: ghcr.io/ebispot/zooma2_frontend:{{.Values.imageTag}}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /data
              name: caddy-data
            - mountPath: /config
              name: caddy-config
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              memory: 1Gi
              cpu: 0.25
            limits:
              memory: 1Gi
              cpu: 0.5
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /spot/zooma/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /spot/zooma/
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: PUBLIC_URL
              value: /spot/zooma/
